# Generated by Django 2.2 on 2020-03-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200314_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ManyToManyField(related_name='received_message', to='user_app.User')),
                ('sender', models.ManyToManyField(related_name='sent_message', to='user_app.User')),
            ],
        ),
    ]
