# Generated by Django 2.2 on 2020-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ManyToManyField(related_name='received_messages', to='user_app.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ManyToManyField(related_name='sent_messages', to='user_app.User'),
        ),
    ]
