# Generated by Django 2.2 on 2020-03-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20200317_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to='user_app.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ManyToManyField(related_name='sender', to='user_app.User'),
        ),
    ]
