# Generated by Django 2.2 on 2020-03-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_auto_20200317_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ManyToManyField(related_name='users', to='user_app.User'),
        ),
    ]
