# Generated by Django 2.2 on 2020-03-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_auto_20200317_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ManyToManyField(related_name='messages', to='user_app.User'),
        ),
    ]
