# Generated by Django 2.2 on 2020-03-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_auto_20200317_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pair',
            field=models.ManyToManyField(related_name='pair', to='user_app.User'),
        ),
    ]
