# Generated by Django 2.2 on 2020-03-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_message_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pair',
        ),
    ]
