# Generated by Django 2.2 on 2020-03-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_remove_message_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ManyToManyField(related_name='sender', to='user_app.User'),
        ),
    ]
