# Generated by Django 2.2 on 2020-03-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_active',
            field=models.BooleanField(default=False),
        ),
    ]
