# Generated by Django 2.2 on 2020-03-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_cart_promo_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
