# Generated by Django 2.2 on 2020-03-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_auto_20200303_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='cart',
            field=models.ManyToManyField(related_name='products', to='shop_app.Cart'),
        ),
    ]
