# Generated by Django 2.2 on 2020-03-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0017_auto_20200304_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='cart', to='shop_app.CartProduct'),
        ),
    ]
