# Generated by Django 2.2 on 2020-03-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0020_auto_20200310_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
