# Generated by Django 2.2 on 2020-03-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0021_cartproduct_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='ordered',
        ),
    ]
