# Generated by Django 2.2 on 2020-03-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0026_auto_20200314_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cvv',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
